# Generated by Django 2.2.3 on 2019-07-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190725_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='Imagem'),
        ),
    ]
