# Generated by Django 2.2.3 on 2019-07-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190725_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criando em'),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
    ]
