# Generated by Django 2.2.3 on 2019-07-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190726_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculo',
            name='start_date',
        ),
    ]
