# Generated by Django 2.2.3 on 2019-08-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_curriculo_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Curriculo'),
        ),
    ]
